### ISSUE TITLE
The counter is not shown

### ISSUE THREAD

**Issue by ImAmirhv** [DanWin/hit-counter#3]
When the user registers and puts the code on his website, the counter is not shown
![test](https://github.com/DanWin/hit-counter/assets/86143719/c51fb0b9-17e1-44aa-966d-4d67faa65fdc)

**Comment by DanWin** [comment]
Hello @ImAmirhv Looks like there is an error generating the image. Check the error logs of your web server for a hint on what is going wrong.

**Comment by ImAmirhv** [comment]
I didnt find anything related to the problem

**Comment by DanWin** [comment]
Then unfortunately there is little I can do to help you. You could try downloading the image file and looking into it with a text editor. Maybe the file itself contains an error message.

**Comment by ImAmirhv** [comment]
i found this error:

The resource at “http://site.onion/hit-counter/counter.php?id=1b7d8d7f913f5e9f84fcdc17b7cc2190&bg=000000&fg=FFFFFF&tr=0&unique=0&mode=0” was blocked due to its Cross-Origin-Resource-Policy header (or lack thereof). See https://developer.mozilla.org/docs/Web/HTTP/Cross-Origin_Resource_Policy_(CORP)# 

Request to access cookie or storage on “http://site.onion/hit-counter/counter.php?id=1b7d8d7f913f5e9f84fcdc17b7cc2190&bg=000000&fg=FFFFFF&tr=0&unique=0&mode=0” was blocked because we are blocking all third-party storage access requests and content blocking is enabled.

any help?

**Comment by DanWin** [comment]
This should now be fixed in the latest commit.
